// <auto-generated />
using System;
using GlassOnTheStreet.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassOnTheStreet.Web.Data.Migrations
{
    [DbContext(typeof(GlassOnTheStreetContext))]
    [Migration("20261001202800_AddMpdIncidents")]
    partial class AddMpdIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.MpdIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CrimeAgainst")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<short>("CrimeCount")
                        .HasColumnType("smallint");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsCrime")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateOnly>("OccurredDate")
                        .HasColumnType("date");

                    b.Property<byte>("OccurredHour")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Offense")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OffenseCategory")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<byte?>("Precinct")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("Ward")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.HasIndex("OccurredDate");

                    b.ToTable("MpdIncidents");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.OneTimeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("OneTimeTasks");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AlternateCaseNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CrimeCount")
                        .HasColumnType("int");

                    b.Property<string>("CrossStreets")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DisplayLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("DisplayLng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ExternalCaseNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<bool?>("ItemsStolen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MpdIncidentId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("MpdReportedDate")
                        .HasColumnType("date");

                    b.Property<string>("MpdType")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("NibrsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NibrsCrimeAgainst")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NibrsGroup")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Offense")
                        .HasColumnType("longtext");

                    b.Property<string>("OffenseCategory")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<bool?>("PoliceReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Precinct")
                        .HasColumnType("int");

                    b.Property<string>("ProblemFinal")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ProblemInitial")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateOnly>("ReportedDate")
                        .HasColumnType("date");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeOfDay")
                        .HasColumnType("int");

                    b.Property<int?>("Ward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCaseNumber")
                        .IsUnique()
                        .HasFilter("`ExternalCaseNumber` IS NOT NULL");

                    b.HasIndex("ReportedDate");

                    b.HasIndex("Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.ReportFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFlags");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.SyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SyncStatuses");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.ReportFlag", b =>
                {
                    b.HasOne("GlassOnTheStreet.Web.Models.Report", "Report")
                        .WithMany("Flags")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.Report", b =>
                {
                    b.Navigation("Flags");
                });
#pragma warning restore 612, 618
        }
    }
}
