// <auto-generated />
using System;
using GlassOnTheStreet.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassOnTheStreet.Web.Data.Migrations
{
    [DbContext(typeof(GlassOnTheStreetContext))]
    [Migration("20260925145927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CrossStreets")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DisplayLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("DisplayLng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<bool?>("ItemsStolen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<bool?>("PoliceReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PreciseLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("PreciseLng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateOnly>("ReportedDate")
                        .HasColumnType("date");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedDate");

                    b.HasIndex("Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.ReportFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFlags");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.ReportFlag", b =>
                {
                    b.HasOne("GlassOnTheStreet.Web.Models.Report", "Report")
                        .WithMany("Flags")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GlassOnTheStreet.Web.Models.Report", b =>
                {
                    b.Navigation("Flags");
                });
#pragma warning restore 612, 618
        }
    }
}
